name: Lint code
on:
  pull_request:
    paths:
      - '.github/workflows/run-lint.yml'
      - '@methodical-js/core/src/**'
      - '@methodical-js/web/src/**'
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn
      - name: Run lint
        run: yarn lint
