name: Test web
on:
  pull_request:
    paths:
      - '.github/workflows/run-core-tests.yml'
      - '@methodical-js/web/src/**'
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn
      - name: Run tests
        working-directory: '@methodical-js/web'
        run: yarn test
